### ISSUE TITLE
Document iam permissions required to use this

### ISSUE THREAD

**Issue by softprops** [softprops/xray#3]
```
 iamRoleStatements:
    - Effect: Allow
      Action:
        - 'xray:PutTraceSegments'
        - 'xray:PutTelemetryRecords'
      Resource:
        - '*'
```
